# Generated by Django 3.2.8 on 2021-10-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0002_auto_20211011_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='skill_tags',
            field=models.ManyToManyField(blank=True, to='RestAPI.SkillTag'),
        ),
    ]
