# Generated by Django 3.2.8 on 2021-10-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0004_auto_20211016_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='pid',
            field=models.CharField(max_length=255),
        ),
    ]
