# Generated by Django 3.2.8 on 2021-11-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0007_auto_20211116_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='first_name',
            field=models.CharField(default='John', max_length=255),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='last_name',
            field=models.CharField(default='Doe', max_length=255),
        ),
    ]
